apiVersion: apps/v1
kind: Deployment
metadata:
  name: fp-hello-world-deployment
  labels:
    env: PROD
spec:
  replicas: 2
  selector:
    matchLabels:
      env: PROD
  template:
    metadata:
      labels:
        env: PROD
    spec:
      containers:
      - name: fphelloworld
        image: sheree1986/fp_hello_world
        ports:
        - containerPort: 80