
version: 2.1

jobs:
  build-docker-image:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv ~/.devops
            source ~/.devops/bin/activate
      - run:
          name: code linting 
          command: |      
            source ~/.devops/bin/activate
            make install
            make lint   
      - setup_remote_docker:
          docker_layer_caching: true            
      - run:
          name: docker code building 
          command: |   
            source ~/.devops/bin/activate          
            docker build --tag=p_hello_world .
            docker image ls	  
      - run:
          name: docker code uploading  
          command: |   
            docker image ls	 
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker tag lastest $DOCKER_USER/fp_hello_world
            docker push sheree1986/fp_hello_world:latest
            
  deploy-docker-image:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: configure aws 
          command: |
            aws configure set aws_access_key_id $ACCESS_KEY_ID
            aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
            aws configure set region $REGION
            aws --version
      - run:
          name: install kubectl and deploy
          command: |          
            curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.16.8/2020-04-16/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            kubectl version --short --client
            aws eks update-kubeconfig --name PROD --region $REGION           
            if [[ `kubectl get deployment | grep fphelloworld` = *"fphelloworld"* ]]
            then
                  echo "i am in"
                  kubectl rollout restart deployment/fp-helloworld-deployment
            else
                  echo "i am out"
                  sleep 10
                  kubectl get service
                  kubectl apply -f fp_hello_world_deployment.yml
                  kubectl get deployment
                  kubectl get pods
                fi
workflows:
  default:
    jobs:
      - build-docker-image
      - deploy-docker-image:
          requires: [build-docker-image]     